### ISSUE TITLE
Issues with archive.is

### ISSUE THREAD

**Issue by jbrunelle** [Thing342/MobileMemento#13]
Looks like we're still not submitting the URIs to archive.is properly. Have you checked to make sure this works? That is, check for mementos in archive.is:
https://archive.is/http://www.justinfbrunelle.com/

and then use mobilemink to push it to archive.is and see if the latest memento gets updated?
When I follow this recipe, I don't see mementos created for www.justinfbrunelle.com/ or http://csnbbs.com/forumdisplay.php?fid=688

**Comment by wjorda** [comment]
This should be fixed in v0.6. Archive.is's API requires one to use HTTP POST data to supply the URL, as opposed to data appended to the URI.
