### ISSUE TITLE
Mementos with No TimeMaps

### ISSUE THREAD

**Issue by jbrunelle** [Thing342/MobileMemento#6]
Need to make sure that URI-Ms don't cause the app to crash. Need to put in a short-circuit when a timemap with no mementos is found, as well as a way to fail gracefully if we get to a crash state.

**Comment by wjorda** [comment]
Duplicate of #3

**Comment by jbrunelle** [comment]
?Excellent. Thanks, Wes!

Justin F. Brunelle
Old Dominion University Department of Computer Science

## Web Science and Digital Libraries Research Group - PhD Student

Engineering & Computational Sciences Bldg
4700 Elkhorn Ave, Suite 3300
Norfolk, VA 23529-0162
E-Mail:            jbrunelle@cs.odu.edu
Cell Phone:      757-536-1586
Fax:                757-826-8316

**Comment by wjorda** [comment]
Should be fixed with latest commit
